import { ApiProperty } from '@nestjs/swagger';
import { Ban } from '@prisma/client';

class BanModel implements Ban {
	@ApiProperty({ description: 'Ban id generated by database' })
	id: string;

	@ApiProperty({ description: 'Channel id' })
	channelId: string;

	@ApiProperty({ description: 'User id' })
	userId: string;

	@ApiProperty({ required: false })
	createdAt: Date;

	@ApiProperty({ required: false })
	updatedAt: Date;
}

export default BanModel;
