import { ApiProperty } from '@nestjs/swagger';
import { ChatRoom } from '@prisma/client';

class ChatRoomModel implements ChatRoom {
	@ApiProperty({ description: 'Chat room id generated by database' })
	id: string;

	@ApiProperty({ description: 'Source user id' })
	srcId: string;

	@ApiProperty({ description: 'Dest user id' })
	destId: string;

	@ApiProperty({ required: false })
	createdAt: Date;

	@ApiProperty({ required: false })
	updatedAt: Date;
}

export default ChatRoomModel;
