import { ApiProperty } from '@nestjs/swagger';
import { $Enums, GameHistory } from '@prisma/client';

class GameHistoryModel implements GameHistory {
	@ApiProperty({ description: 'Game history id generated by database' })
	id: string;

	@ApiProperty({ description: 'Game id generated by database' })
	gameId: string;

	@ApiProperty({ description: 'Player 1 id' })
	player1Id: string;

	@ApiProperty({ description: 'Player 2 id' })
	player2Id: string;

	@ApiProperty({ description: 'Game mode' })
	mode: $Enums.GameMode;

	@ApiProperty({ description: 'Player 1 score' })
	player1Score: number;

	@ApiProperty({ description: 'Player 2 score' })
	player2Score: number;

	@ApiProperty({ description: 'Game result' })
	result: $Enums.GameResult;

	@ApiProperty({ required: false })
	createdAt: Date;

	@ApiProperty({ required: false })
	updatedAt: Date;
}

export default GameHistoryModel;
