import { ApiProperty } from '@nestjs/swagger';
import { Mute } from '@prisma/client';

class MuteModel implements Mute {
	@ApiProperty({ description: 'Mute id generated by database' })
	id: string;

	@ApiProperty({ description: 'Channel id' })
	channelId: string;

	@ApiProperty({ description: 'User id' })
	userId: string;

	@ApiProperty({ required: false })
	createdAt: Date;

	@ApiProperty({ required: false })
	updatedAt: Date;
}

export default MuteModel;
