import { ApiProperty } from '@nestjs/swagger';
import { User, UserStatus } from '@prisma/client';

class UserModel implements User {
	@ApiProperty({ description: 'User id generated by database' })
	id: string;

	@ApiProperty({ description: 'Intra id' })
	intraId: string;

	@ApiProperty({ description: 'Nickname', required: false, default: null, nullable: true })
	nickname: string;

	@ApiProperty({ description: 'Index image URI', required: false, default: null, nullable: true })
	profileImageURI: string;

	@ApiProperty({
		description: 'Email used for 2FA',
		required: false,
		default: null,
		nullable: true,
	})
	email2fa: string;

	@ApiProperty({ description: 'State of using 2FA', required: false, default: false })
	use2fa: boolean;

	@ApiProperty({ description: 'Status of user', required: false, default: UserStatus.OFFLINE })
	status: UserStatus;

	@ApiProperty({ required: false })
	createdAt: Date;

	@ApiProperty({ required: false })
	updatedAt: Date;
}

export default UserModel;
