FROM node:21-alpine3.19

LABEL 	name="NestJS" \
		version="1.0" \
		description="NestJS"

EXPOSE 3000

ENV HOME /app

WORKDIR $HOME

COPY . .

COPY ./tool/docker-entrypoint.sh /usr/local/bin/

RUN cp ./tool/docker-entrypoint.sh /usr/local/bin/ && \
	chmod +x /usr/local/bin/docker-entrypoint.sh

RUN yarn install --frozen-lockfile && yarn build

ENTRYPOINT [ "docker-entrypoint.sh" ]

CMD [ "yarn", "run", "dev" ]