import { ApiProperty } from '@nestjs/swagger';

export class Update {
	// @ApiProperty({ description: 'User id generated by database'
	// })
	// id: string;

	@ApiProperty({ description: 'Nickname', example: 'younhwan' })
	nickname: string;

	// @ApiProperty({ description: 'Profile image URI', nullable: true })
	// profileImageURI: string;
	
	// @ApiProperty({ description: 'email', nullable: true })
	// email2fa: string;
}
