import { ApiProperty } from '@nestjs/swagger';
import { IsOptional } from 'class-validator';

export class ChatRoom {
	@ApiProperty({ description: 'Chat room id generated by database' })
	id: string;

	@ApiProperty({ description: 'Source user id' })
	srcId: string;

	@ApiProperty({ description: 'Dest user id' })
	destId: string;

	@IsOptional()
    @ApiProperty({ description: 'Dest user nickname' })
    destNickname: string;

	@ApiProperty({ required: false })
	createdAt: Date;

	@ApiProperty({ required: false })
	updatedAt: Date;
}